### ISSUE TITLE
Error message on macOS

### ISSUE THREAD

**Issue by Aimonius** [TransUrban-UAH/Cadastral_Classifier#2]
Greetings. When I try to use the plugin I get this error message.

```
WARNING    Traceback (most recent call last):
              File "/Users/xxxxxx/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Cadastral_Classifier/cadastral_classifier.py", line 1104, in setup_data
              wd_urb = unzip_shp(urban_SHP_file_path)
              File "/Users/xxxxxx/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Cadastral_Classifier/utils/shp_utils.py", line 65, in unzip_shp
              return dest_filepath + "/" + shp_name[0]
             IndexError: list index out of range

```
I'm using QGIS 3.24.0 on macOS 10.15
Python version 3.9.5

Regards.

**Comment by TransUrban-UAH** [comment]
Apologies, didn't have the chance to test and track issues on macOS. Updated to a new version which solved and improved many aspects. Let me know if it still happening.
