### ISSUE TITLE
Error en el proceso Tratamiento de datos

### ISSUE THREAD

**Issue by acanivano** [TransUrban-UAH/Cadastral_Classifier#6]
Buenas tardes. Cuando relleno los datos de la aplicación, según me lo pide (ver imagen adjunta) aparece este mensaje. ¿alguna idea
? Gracias![image](https://github.com/TransUrban-UAH/Cadastral_Classifier/assets/25487136/a5b1e3d5-e871-47ac-83e6-41b3bd169f23)

**2024-06-07T13:51:38     WARNING    Traceback (most recent call last):
              File "C:\Users/acañivano/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Cadastral_Classifier\cadastral_classifier.py", line 3268, in setup_data
              task = setup_data_Task(self.dlg, self.d_codes, self.get_selected_mun())
              ^^^^^^^^^^^^
             AttributeError: 'cadastral_classifier' object has no attribute 'd_codes'**

**Comment by nairdri** [comment]
Hola, tengo el mismo error, lo has conseguido solucionar??

**Comment by salvagzpr** [comment]
Hola! yo también tengo el mismo problema. Contacté con el desarrollador del plug-in y me dijo que está solucionandolo, y que subirá una actualización del plug-in.

Me recomendó utilizar versiones antiguas de QGIS o trabajar con la pestaña de varios municipio y realizar un filtrado. Intentando lo segundo he seguido obteniendo error...

**Comment by maxitenerife** [comment]
Igual:

2025-02-28T08:43:39     WARNING    Traceback (most recent call last):
              File "C:\Users/XXX/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Cadastral_Classifier\cadastral_classifier.py", line 3268, in setup_data
              task = setup_data_Task(self.dlg, self.d_codes, self.get_selected_mun())
             AttributeError: 'cadastral_classifier' object has no attribute 'd_codes'

A veces funciona y otras no, no sé a que se debe el error.

**Comment by nikoshur** [comment]
Hola a todos:
Disculpad la demora en responder. La nueva versión del plugin (3.5) soluciona este error. Se ha testeado en la última versión LTR de QGIS (3.40). En los próximos días estará disponible en el repositorio de QGIS, aunque ya podéis descargarla desde aquí.

**Comment by acanivano** [comment]
Gracias!!

**Comment by salvagzpr** [comment]
Muchas gracias!

**Comment by maxitenerife** [comment]
Muchas gracias!!
